# Generated by Django 4.1.7 on 2023-03-02 04:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stat', models.CharField(choices=[('HP', 'HP'), ('ATK', 'Attack'), ('DEF', 'Defense'), ('SP. ATK', 'Sp. Atk'), ('SP. DEF', 'Sp. Def'), ('SPD', 'Speed')], default='HP', max_length=7)),
                ('EVs', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(252), django.core.validators.MinValueValidator(0)])),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.pokemon')),
            ],
        ),
    ]
