# Generated by Django 4.1.7 on 2023-03-11 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_pokemon_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='items',
            new_name='item',
        ),
    ]
